### ISSUE TITLE
Support Javascript-style millisecond timestamps

### ISSUE THREAD

**Issue by blixt** [TotempaaltJ/unix.click#4]
`100000000000` is year 5138 so it's pretty safe to assume that higher values were actually not a UNIX seconds-since-1970 timestamp, but rather a JavaScript milliseconds-since-1970 one.

(this automagic does mean you can't do JS timestamps before March 3, 1973 tho, unless there's an explicit option)

**Comment by martijnarts** [comment]
The two suggested solutions:

* Treating timestamp >= 100,000,000,000 as a JavaScript timestamp
* Adding an explicit option to trigger millisecond timestamp calculation

I'm personally partial to the latter, so that all millisecond timestamps work (including before 1973-03-03), but there might be a good way to combine both, like automatically enabling the option when entering timestamps above 1e11.

**Comment by chris13524** [comment]
What if there were two fields? One being seconds since epoch and the other being milliseconds since epoch?
